name = "This & that"
creator = "TenBitMelon"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "N2E4MWQyMWI2OGYwNjE1MjVkOWFhM2NmNjk4ZmEzYTczZDZiYTdhZmUxOTZkYWZkNGYyZDYzMDUwYTkzMTQ2Nw=="

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"